import { NextRequest } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { supabaseAdmin } from '@/lib/supabase/admin'

interface RequestBody {
  email: string
  courseId: number
}

export async function POST(request: NextRequest) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) {
    return Response.json({ error: 'Unauthorized' }, { status: 401 })
  }

  // Verify admin
  const { data: profile } = await supabase
    .from('profiles')
    .select('is_admin')
    .eq('id', user.id)
    .single()

  if (!profile?.is_admin) {
    return Response.json({ error: 'Forbidden: admin access required' }, { status: 403 })
  }

  let body: RequestBody
  try {
    body = await request.json()
  } catch {
    return Response.json({ error: 'Invalid JSON' }, { status: 400 })
  }

  const { email, courseId } = body

  if (!email || !courseId) {
    return Response.json({ error: 'email and courseId are required' }, { status: 400 })
  }

  // Verify course exists
  const { data: course } = await supabaseAdmin
    .from('courses')
    .select('id')
    .eq('id', courseId)
    .single()

  if (!course) {
    return Response.json({ error: 'Course not found' }, { status: 404 })
  }

  // Create invite record (token is auto-generated by DB default)
  const { data: invite, error: inviteError } = await supabaseAdmin
    .from('invites')
    .insert({
      course_id: courseId,
      email: email.toLowerCase().trim(),
    })
    .select('token')
    .single()

  if (inviteError || !invite) {
    console.error('Failed to create invite:', inviteError)
    return Response.json({ error: 'Failed to create invite' }, { status: 500 })
  }

  // Build invite URL
  const baseUrl = request.headers.get('origin') ?? process.env.NEXT_PUBLIC_SITE_URL ?? 'http://localhost:3000'
  const inviteUrl = `${baseUrl}/register/${invite.token}`

  return Response.json({ inviteUrl, token: invite.token })
}
